import 'package:minutes_magic_app/app/modules/allcategory/model/product_model.dart';

final List<ProductModel> riceProducts = [
  ProductModel(
    id: 'rice1',
    name: "Ponni Rice",
    price: 140,
    oldPrice: 160,
    unit: "1kg",
    image: "assets/images/rice.png",
  ),
  ProductModel(
    id: 'rice2',
    name: "Red Rice",
    price: 105,
    oldPrice: 120,
    unit: "1kg",
    image: "assets/images/rice.png",
  ),
  ProductModel(
    id: 'rice3',
    name: "Sticky Rice",
    price: 125,
    oldPrice: 140,
    unit: "1kg",
    image: "assets/images/rice.png",
  ),
  ProductModel(
    id: 'rice4',
    name: "Basmati Rice",
    price: 180,
    oldPrice: 210,
    unit: "1kg",
    image: "assets/images/rice.png",
  ),
  ProductModel(
    id: 'rice5',
    name: "Brown Rice",
    price: 135,
    oldPrice: 155,
    unit: "1kg",
    image: "assets/images/rice.png",
  ),
  ProductModel(
    id: 'rice6',
    name: "Jeera Samba Rice",
    price: 160,
    oldPrice: 190,
    unit: "1kg",
    image: "assets/images/rice.png",
  ),
  ProductModel(
    id: 'rice7',
    name: "Matta Rice",
    price: 100,
    oldPrice: 115,
    unit: "1kg",
    image: "assets/images/rice.png",
  ),
  ProductModel(
    id: 'rice8',
    name: "Sona Masoori Rice",
    price: 130,
    oldPrice: 150,
    unit: "1kg",
    image: "assets/images/rice.png",
  ),
  ProductModel(
    id: 'rice9',
    name: "Black Rice",
    price: 150,
    oldPrice: 175,
    unit: "1kg",
    image: "assets/images/rice.png",
  ),
];

final List<ProductModel> drinkProducts = [
  ProductModel(
    id: 'drink1',
    name: 'Orange Juice',
    price: 50,
    oldPrice: 60,
    unit: '500ml',
    image: 'assets/images/drinks.png',
  ),
  ProductModel(
    id: 'drink2',
    name: 'Apple Juice',
    price: 55,
    oldPrice: 65,
    unit: '500ml',
    image: 'assets/images/drinks.png',
  ),
  ProductModel(
    id: 'drink3',
    name: 'Mango Juice',
    price: 60,
    oldPrice: 70,
    unit: '1L',
    image: 'assets/images/drinks.png',
  ),
  ProductModel(
    id: 'drink4',
    name: 'Lemonade',
    price: 45,
    oldPrice: 55,
    unit: '200ml',
    image: 'assets/images/drinks.png',
  ),
  ProductModel(
    id: 'drink5',
    name: 'Coconut Water',
    price: 70,
    oldPrice: 80,
    unit: '750ml',
    image: 'assets/images/drinks.png',
  ),
  ProductModel(
    id: 'drink6',
    name: 'Grape Juice',
    price: 65,
    oldPrice: 75,
    unit: '1L',
    image: 'assets/images/drinks.png',
  ),
  ProductModel(
    id: 'drink7',
    name: 'Pineapple Juice',
    price: 52,
    oldPrice: 60,
    unit: '500ml',
    image: 'assets/images/drinks.png',
  ),
  ProductModel(
    id: 'drink8',
    name: 'Pomegranate Juice',
    price: 58,
    oldPrice: 68,
    unit: '1L',
    image: 'assets/images/drinks.png',
  ),
];

final List<ProductModel> dryfruitProducts = [
  ProductModel(
    id: 'dry1',
    name: 'Almonds',
    price: 200,
    oldPrice: 220,
    unit: '250g',
    image: 'assets/images/Dry Fruits.png',
  ),
  ProductModel(
    id: 'dry2',
    name: 'Cashews',
    price: 250,
    oldPrice: 280,
    unit: '250g',
    image: 'assets/images/Dry Fruits.png',
  ),
  ProductModel(
    id: 'dry3',
    name: 'Raisins',
    price: 180,
    oldPrice: 200,
    unit: '500g',
    image: 'assets/images/Dry Fruits.png',
  ),
  ProductModel(
    id: 'dry4',
    name: 'Walnuts',
    price: 270,
    oldPrice: 300,
    unit: '250g',
    image: 'assets/images/Dry Fruits.png',
  ),
  ProductModel(
    id: 'dry5',
    name: 'Pistachios',
    price: 260,
    oldPrice: 290,
    unit: '250g',
    image: 'assets/images/Dry Fruits.png',
  ),
  ProductModel(
    id: 'dry6',
    name: 'Dates',
    price: 220,
    oldPrice: 240,
    unit: '250g',
    image: 'assets/images/Dry Fruits.png',
  ),
  ProductModel(
    id: 'dry7',
    name: 'Figs',
    price: 230,
    oldPrice: 250,
    unit: '500g',
    image: 'assets/images/Dry Fruits.png',
  ),
  ProductModel(
    id: 'dry8',
    name: 'Hazelnuts',
    price: 240,
    oldPrice: 260,
    unit: '250g',
    image: 'assets/images/Dry Fruits.png',
  ),
];

final List<ProductModel> eggProducts = [
  ProductModel(
    id: 'egg1',
    name: 'Country Eggs',
    price: 70,
    oldPrice: 80,
    unit: '6 pcs',
    image: 'assets/images/eggs.png',
  ),
  ProductModel(
    id: 'egg2',
    name: 'Brown Eggs',
    price: 75,
    oldPrice: 85,
    unit: '6 pcs',
    image: 'assets/images/eggs.png',
  ),
  ProductModel(
    id: 'egg3',
    name: 'White Eggs',
    price: 60,
    oldPrice: 70,
    unit: '12 pcs',
    image: 'assets/images/eggs.png',
  ),
  ProductModel(
    id: 'egg4',
    name: 'Quail Eggs',
    price: 65,
    oldPrice: 75,
    unit: '12 pcs',
    image: 'assets/images/eggs.png',
  ),
  ProductModel(
    id: 'egg5',
    name: 'Duck Eggs',
    price: 68,
    oldPrice: 78,
    unit: '6 pcs',
    image: 'assets/images/eggs.png',
  ),
  ProductModel(
    id: 'egg6',
    name: 'Omega Eggs',
    price: 80,
    oldPrice: 90,
    unit: '6 pcs',
    image: 'assets/images/eggs.png',
  ),
  ProductModel(
    id: 'egg7',
    name: 'Organic Eggs',
    price: 72,
    oldPrice: 82,
    unit: '12 pcs',
    image: 'assets/images/eggs.png',
  ),
  ProductModel(
    id: 'egg8',
    name: 'Free-range Eggs',
    price: 78,
    oldPrice: 88,
    unit: '6 pcs',
    image: 'assets/images/eggs.png',
  ),
];

final List<ProductModel> breadProducts = [
  ProductModel(
    id: 'bread1',
    name: 'Whole Wheat Bread',
    price: 40,
    oldPrice: 48,
    unit: '400g',
    image: 'assets/images/bread.png',
  ),
  ProductModel(
    id: 'bread2',
    name: 'White Sandwich Bread',
    price: 35,
    oldPrice: 42,
    unit: '400g',
    image: 'assets/images/bread.png',
  ),
  ProductModel(
    id: 'bread3',
    name: 'Multigrain Bread',
    price: 50,
    oldPrice: 60,
    unit: '500g',
    image: 'assets/images/bread.png',
  ),
  ProductModel(
    id: 'bread4',
    name: 'Brown Bread',
    price: 45,
    oldPrice: 52,
    unit: '450g',
    image: 'assets/images/bread.png',
  ),
  ProductModel(
    id: 'bread5',
    name: 'Oat Bread',
    price: 38,
    oldPrice: 45,
    unit: '400g',
    image: 'assets/images/bread.png',
  ),
  ProductModel(
    id: 'bread6',
    name: 'Rye Bread',
    price: 48,
    oldPrice: 55,
    unit: '500g',
    image: 'assets/images/bread.png',
  ),
  ProductModel(
    id: 'bread7',
    name: 'Garlic Bread',
    price: 42,
    oldPrice: 50,
    unit: '300g',
    image: 'assets/images/bread.png',
  ),
  ProductModel(
    id: 'bread8',
    name: 'Baguette',
    price: 55,
    oldPrice: 65,
    unit: '1pc',
    image: 'assets/images/bread.png',
  ),
];

final List<ProductModel> fruitProducts = [
  ProductModel(
    id: 'fruit1',
    name: 'Mango',
    price: 90,
    oldPrice: 100,
    unit: '1kg',
    image: 'assets/images/fruits.png',
  ),
  ProductModel(
    id: 'fruit2',
    name: 'Apple',
    price: 120,
    oldPrice: 135,
    unit: '1kg',
    image: 'assets/images/fruits.png',
  ),
  ProductModel(
    id: 'fruit3',
    name: 'Banana',
    price: 60,
    oldPrice: 70,
    unit: '1 dozen',
    image: 'assets/images/fruits.png',
  ),
  ProductModel(
    id: 'fruit4',
    name: 'Grapes',
    price: 80,
    oldPrice: 95,
    unit: '500g',
    image: 'assets/images/fruits.png',
  ),
  ProductModel(
    id: 'fruit5',
    name: 'Orange',
    price: 70,
    oldPrice: 85,
    unit: '1kg',
    image: 'assets/images/fruits.png',
  ),
  ProductModel(
    id: 'fruit6',
    name: 'Papaya',
    price: 85,
    oldPrice: 100,
    unit: '1kg',
    image: 'assets/images/fruits.png',
  ),
  ProductModel(
    id: 'fruit7',
    name: 'Pineapple',
    price: 95,
    oldPrice: 110,
    unit: '1kg',
    image: 'assets/images/fruits.png',
  ),
  ProductModel(
    id: 'fruit8',
    name: 'Watermelon',
    price: 110,
    oldPrice: 125,
    unit: '1pc',
    image: 'assets/images/fruits.png',
  ),
];

final List<ProductModel> vegetableProducts = [
  ProductModel(
    id: 'veg1',
    name: 'Tomatoes',
    price: 30,
    oldPrice: 35,
    unit: '1kg',
    image: 'assets/images/vegetable.png',
  ),
  ProductModel(
    id: 'veg2',
    name: 'Onions',
    price: 25,
    oldPrice: 30,
    unit: '1kg',
    image: 'assets/images/vegetable.png',
  ),
  ProductModel(
    id: 'veg3',
    name: 'Potatoes',
    price: 20,
    oldPrice: 25,
    unit: '1kg',
    image: 'assets/images/vegetable.png',
  ),
  ProductModel(
    id: 'veg4',
    name: 'Carrots',
    price: 28,
    oldPrice: 35,
    unit: '500g',
    image: 'assets/images/vegetable.png',
  ),
  ProductModel(
    id: 'veg5',
    name: 'Cabbage',
    price: 22,
    oldPrice: 30,
    unit: '1kg',
    image: 'assets/images/vegetable.png',
  ),
  ProductModel(
    id: 'veg6',
    name: 'Spinach',
    price: 24,
    oldPrice: 28,
    unit: '1 bunch',
    image: 'assets/images/vegetable.png',
  ),
  ProductModel(
    id: 'veg7',
    name: 'Cucumber',
    price: 26,
    oldPrice: 30,
    unit: '500g',
    image: 'assets/images/vegetable.png',
  ),
  ProductModel(
    id: 'veg8',
    name: 'Capsicum',
    price: 32,
    oldPrice: 38,
    unit: '1kg',
    image: 'assets/images/vegetable.png',
  ),
];

final List<ProductModel> spiceProducts = [
  ProductModel(
    id: 'spice1',
    name: 'Turmeric Powder',
    price: 60,
    oldPrice: 70,
    unit: '200g',
    image: 'assets/images/spices.png',
  ),
  ProductModel(
    id: 'spice2',
    name: 'Red Chilli Powder',
    price: 70,
    oldPrice: 80,
    unit: '200g',
    image: 'assets/images/spices.png',
  ),
  ProductModel(
    id: 'spice3',
    name: 'Coriander Powder',
    price: 65,
    oldPrice: 75,
    unit: '100g',
    image: 'assets/images/spices.png',
  ),
  ProductModel(
    id: 'spice4',
    name: 'Cumin Powder',
    price: 68,
    oldPrice: 78,
    unit: '150g',
    image: 'assets/images/spices.png',
  ),
  ProductModel(
    id: 'spice5',
    name: 'Garam Masala',
    price: 75,
    oldPrice: 90,
    unit: '200g',
    image: 'assets/images/spices.png',
  ),
  ProductModel(
    id: 'spice6',
    name: 'Black Pepper',
    price: 62,
    oldPrice: 72,
    unit: '100g',
    image: 'assets/images/spices.png',
  ),
  ProductModel(
    id: 'spice7',
    name: 'Cardamom',
    price: 80,
    oldPrice: 95,
    unit: '50g',
    image: 'assets/images/spices.png',
  ),
  ProductModel(
    id: 'spice8',
    name: 'Clove',
    price: 85,
    oldPrice: 98,
    unit: '100g',
    image: 'assets/images/spices.png',
  ),
];
